### ISSUE TITLE
Error "can't use a named cursor outside of transactions"

### ISSUE THREAD

**Issue by lapshin1988** [chtd/psycopg2cffi#82] opened 2017-04-24 09:33 UTC
Hello!

I try use psycopg2cffi in my django project. When I run django tests `(pypy manage.py test),` I get an error "cursor "_django_curs_<...>" does not exist". 
While debugging the code, I determined that original exception is "can't use a named cursor outside of transactions" (_impl/cursor.py:):
```
if self._name:
    if self._query:
        raise ProgrammingError("can't call .execute() on named cursors more than once")
    if self._conn.autocommit:
        raise ProgrammingError("can't use a named cursor outside of transactions")
```
By default in Django autocommit == True, and this works on psycopg2, but fail in psycopg2cffi.

Can you help me with this problem?

**Comment by Suor** [comment] 2017-05-04 07:28
Have the same issue. Looks like Django 1.11 switched to database side cursors which don't work in psycopg2cffi.

**Comment by lopuhin** [comment] 2017-05-04 07:56
Hi @Suor and @lapshin1988  - sorry for being unresponsive.
If you have some easy way to reproduce the problem, can you share it? If not, I'll try to run some django tests. Which version of Python are you using?
Database side cursors used to work in psycopg2cffi, but maybe django is using them in a way that is not currently tested.

**Comment by Suor** [comment] 2017-05-04 08:47
I get it when running [cacheops](https://github.com/Suor/django-cacheops) tests agains pypy and Django 1.11 - https://travis-ci.org/Suor/django-cacheops/jobs/228637869

**Comment by strikaco** [comment] 2017-06-28 18:20
I'm experiencing the same issue with the same setup-- pypy, psycopg2cffi and Django 1.11. In my case the error is reproducible in the Admin backend when I try to view/change any individual model instance-- the page does not load, instead throwing this error.

**Comment by the1337guy** [comment] 2017-07-26 18:55
This needs to be fixed.

This caught me when I was initially trying out PyPy with Django.

**Comment by danchr** [comment] 2017-08-11 11:24
AFAICT #81 fixes this; could you please retest?

**Comment by lopuhin** [comment] 2017-08-11 11:28
> AFAICT #81 fixes this; could you please retest?

The fix is in ``psycopg2cffi==2.7.6``

**Comment by stefankoegl** [comment] 2017-09-07 17:04
`psycopg2cffi==2.7.6` fixed my issue in gpodder/mygpo#59. Thanks :)

**Comment by danchr** [comment] 2017-09-11 07:18
@lopuhin No new reports since the release, so I believe you can close this one!

**Comment by lopuhin** [comment] 2017-09-11 07:29
Thanks again for the fix @danchr and everyone for reporting and testing.

**Closed by lopuhin** 2017-09-11 07:29 UTC
